import Head from 'next/head'
import Link from 'next/link'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div style={{backgroundImage: "url('https://www.xtrafondos.com/en/descargar.php?id=3063&resolucion=1280x720')"}} className="bg-cover h-[100vh] bg-fixed">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Link href='/map'>
        <div className='p-1 m-2 rounded-md bg-gradient-to-r from-violet-900 to-fuchsia-800 fixed cursor-pointer'>
          <img src='./map-logo.png' className='w-40 rounded-md'/> 
        </div>
      </Link>
      <img src='./sam-oak.png' className='w-48 fixed bottom-0 left-0'/>
      <div className='flex flex-col justify-center h-screen my-auto items-center font-Bungee text-gray-200'>
        <p className='lg:text-9xl text-6xl skew-x-6'>POKEMON</p>
        <p className='lg:text-6xl text-3xl  skew-x-6 text-yellow-400'>The Delhi Saga</p>
        <Link href='/new'>
          <div className='cursor-pointer my-20 bg-gradient-to-r from-teal-700 to-cyan-900 hover:bg-gradient-to-l rounded-md'>
            <button className='font-Finlandica py-2 px-7 text-3xl'>Explore New Pokemons</button>
          </div>
        </Link>
      </div>
    </div>
  )
}
