import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Map(){
    return(
        <div className="bg-[url('../public/background.jpg')] bg-cover h-[100vh] bg-fixed">
            <Head>
                <title>Map</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <img src="./map.png" className="pt-[6.2rem] h-[43.4rem] w-[40rem] ml-[26rem]" />
        </div>
    )
}